services:
  # Base de Datos
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
      MYSQL_USER: kcepeda
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Backend (Spring Boot)
  backend:
    build: ./banking-management
    container_name: banking_backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: kcepeda
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Frontend (Angular)
  frontend:
    build: ./test.frontend
    container_name: banking_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge